# OpenTelemetry Collector Configuration for Analytics Observability
# Simplified configuration focusing on metrics collection

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.name
        value: "open-webui-analytics"
        action: upsert

  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "openwebui"
    const_labels:
      environment: "production"

  # Debug exporter for troubleshooting
  debug:
    verbosity: basic

service:
  pipelines:
    # Metrics pipeline: OTLP -> Batch -> Prometheus
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, debug]

    # Simple traces pipeline for debugging
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

    # Simple logs pipeline for debugging
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133